### ISSUE TITLE
Still need a lot more mixins

### ISSUE THREAD

**Issue by David-Mulder** [David-Mulder/paper-datatable#17]
Added a fair number today (enough to make a pretty solid theming demo), but still should add more.

**Comment by kersten** [comment]
Would be nice to see how `custom-row-style` works with data-source in the card. I can't get the action executed if I use external data-source in `paper-datatable-card`

**Comment by David-Mulder** [comment]
@kersten It's 'documented' in the `theming.html` demo, check that one out. 99% sure that using a `data-source` shouldn't change that.

**Comment by David-Mulder** [comment]
Closing this issue and instead will rely on separate issues as people miss stuff.
