### ISSUE TITLE
How to pass format-value a function inside a customer Polymer element?

### ISSUE THREAD

**Issue by FraBle** [David-Mulder/paper-datatable#22]
example:

``` javascript
<paper-datatable-column ... format-value="[[formatValue]]" ...> </paper-datatable-column>
```

``` javascript
Polymer({
    is: "xyz",
    ...
    formatValue: function(value){
      return (this._isNumeric(value) ? Number(value).toLocaleString("en-US") : value );
    }
});
```

It won't overwrite the default implementation for formatValue in `paper-datatable-column.html`.

**Comment by David-Mulder** [comment]
Hmm~ pretty sure `dom-bind` is supposed to work the same way as an element, so will take a better look later today.

**Comment by David-Mulder** [comment]
I figured out what's happening... and it sucks, because I am not yet sure how to fix it...

**Comment by David-Mulder** [comment]
@FraBle So, 2 hours later I have a fix. So, for one, you found a big bug and it's now resolved. For two, after the fixes the way to get it working is by writing

```
ready: function(){
  this.set('formatDate', function(value){
    return 'something';
  });
}
```

For reasons I don't get functions on the `this` scope do not seem to work, so yeah, I think I will use

```
this.set('formatDate', this.formatDate);
```

myself once I need it.
