### ISSUE TITLE
How to set classes for columns to use for example --paper-datatable-class-1?

### ISSUE THREAD

**Issue by FraBle** [David-Mulder/paper-datatable#23]

**Comment by David-Mulder** [comment]
Those utility classes can be used to style things inside _cells_, so if you use custom `<template>`'s you can use that class inside and then style it from the outside. Of course you can achieve the same thing with inline styles like in the rest of the component, but I added those utility classes before I decided to just embrace inline styles. Either way, styling column headers is done through `style="color:red"` on the `<paper-datatable-column>`, and the cells in the column through `cell-style="color:green"`. If you haven't seen it yet you might want to check out http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/theming.html
