### ISSUE TITLE
Restrinct scrolling to either asc or desc with sortable attribute

### ISSUE THREAD

**Issue by xmakro** [David-Mulder/paper-datatable#30]
```
<paper-datatable-column sortable="asc">
```

shoud only allow ascending sort (arrow up)

```
<paper-datatable-column sortable="desc">
```

while this should only allow descending order (arrow down)

**Comment by David-Mulder** [comment]
@makrolabs Just for my understanding, could you outline an example where this is useful? I am quite open to implementing this, but at least I wish to understand and confirm the kind of situation where this makes sense.

**Comment by xmakro** [comment]
hi david, an example use case would be Google Drive. If you click on the column headers, they only allow one sorting direction. Often it does not add value to have Z-A sorting. In the current implementation it often requires a double click to select the correct order.

**Comment by David-Mulder** [comment]
@makrolabs Well, Google Drive every sortable column sorts in both directions? I am not sure what you're seeing, but checking both the oldest and the newest files is valuable, as is - to a lesser extent - sorting the name from Z-A.

**Comment by David-Mulder** [comment]
Closing this issue for the time being as feature requesters example use case actually didn't implement the feature. Regarding the double click, I think I fixed a bug along the way where I changed the default sorting direction and you can pre-set a `sort-direction` on a column (though on click it will switch, so you want to set the opposite sorting direction) thus optimizing the user experience even further.
