### ISSUE TITLE
Dynamic adding and removing of `<paper-datatable-column>`'s

### ISSUE THREAD

**Issue by David-Mulder** [David-Mulder/paper-datatable#39]
Per title, isn't working right now for the most part.

**Comment by David-Mulder** [comment]
Not possible till https://github.com/Polymer/polymer/issues/3103 gets fixed (though even once that gets fixed I still need to rewrite a couple of things)

**Comment by NamTThai** [comment]
I recently found your project and it looks amazing. Just a question. I have a couple of use case when table overflow data quite easily. So how do you handle overflow in these 2 cases:

* Overflowing vertically: Do you have a feature for freezing table header and only scrolling table body? I know that you have a feature to only display 10/20 rows but sometimes it would be great to show all the rows.

* Overflowing horizontally: Adding too many columns and it no longer fits on viewport. How do you deal with this? Is there a bottom scrollbar for example?

Thanks for the amazing work!
