### ISSUE TITLE
Creating columns for arrays?

### ISSUE THREAD

**Issue by sevenseat** [David-Mulder/paper-datatable#44]
David - thanks so much for building and sharing this element.  I've found it extremely helpful in my project.  

I'm struggling with implementing one of my usecases... Was hoping you could point me in the right direction.

I have a datatable mapped to an Object "results" which contains an array called "legs".  Is there an idiomatic way to create a column for each item in the legs array?  My first thought was to do a `<dom-repeat>` of `<paper-datatable-columns>` with custom `<template>`s.  However, I haven't figured out how to access the each of the items within the `<template>`.

Is there a simple solution that I haven't found?  I appreciate the guidance!

**Comment by David-Mulder** [comment]
Sorry, I am not able to figure out what you're trying to do exactly based on what you're saying. Would you have an example of the kind of data structure you want to show?

**Comment by David-Mulder** [comment]
And for that matter, I will fix that issue surrounding `<dom-repeat>` and `<paper-datatable-column>`'s not playing nicely together, but that will have to wait till later as I am quite busy the next few days.

**Comment by sevenseat** [comment]
David - appreciate you getting back to me so quickly. I'm trying to generate the following datatable:

| Contestant | Leg 1 Time | Leg 1 Rank | Leg 2 Time | Leg 2 Rank |
| --- | --- | --- | --- | --- |
| Me | 45 | 1 | 30 | 2 |
| You | 50 | 2 | 20 | 1 |

From the following data structure

``` javascript
          var results = [
            {
              name: 'me',
              legs: [
                { time: 45, rank: 1},
                { time: 30, rank: 2}
              ]
            },
            {
              name: 'you',
              legs: [
                { time: 50, rank: 2},
                { time: 20, rank: 1}
              ]
            }
```

The number of `legs` varies, so that's why I'm using an array.  I'm having a bit of trouble figuring out how to dynamically traverse that `legs` array to create a `rank` and `time` column for each.

Does that make more sense?  I appreciate your perspective when you get a shot.  Not a huge rush, this is a nights & weekends project for me.

**Comment by David-Mulder** [comment]
I see, that will indeed definitely require at least the dom-repeat support I mentioned above. Will take a look at it at the end of this week.

**Comment by David-Mulder** [comment]
Yep, dom-repeat should now work and on top of that I have a simple showcase on how to do it: http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/race.html
