### ISSUE TITLE
Firebase intagration

### ISSUE THREAD

**Issue by Negashev** [David-Mulder/paper-datatable#46]
If you use Firebase, then when editing rows in the table after the first editing, breaks "focus" or "binding"
![Imgur](http://i.imgur.com/tLkSdoM.gif?1)

**Comment by David-Mulder** [comment]
@Negashev Given that the content of your screenshot clearly shows sites which destroy my work and worth as a digital content producer I can not understand how you even came up with the idea to ask for help like that... The arrogance simply confounds me. I mean, I don't even know what to say... Like seriously... wt*...

I mean, for one I am a programmer for a living, so it's extremely insulting on it's own, and beyond that, do you seriously think that I am going to partake in criminal behavior by helping you? (And yes, knowingly facilitating illegal behavior is definitely illegal in most countries including mine).

Getting firebase support working was something I actually was looking forward to, but I guess that will have to wait for awhile longer then. Still though, most of all I am just confused how you came up with the idea to walk up to someone who's a victim of your actions, proudly display your wrongdoings and then expect him to help you... like wt*...

**Comment by Negashev** [comment]
I think you have made premature conclusions, Thanks

**Comment by David-Mulder** [comment]
@Negashev I checked your other repositories before I concluded that it didn't seem a service to report and/or analyze behavior of torrenters. If I am wrong please do enlighten me.

**Comment by Negashev** [comment]
I work in PiratePay
