### ISSUE TITLE
Doesn't work in Edge

### ISSUE THREAD

**Issue by David-Mulder** [David-Mulder/paper-datatable#5]
Edge debugger is super crappy, so not sure what's happening, but:

> Unable to get property 'title' of undefined or null reference

Somewhere in paper-datatable.html.js

**Comment by David-Mulder** [comment]
Turns out this has to do with accessing properties set with polymer on the `<tr>` element... :confounded: No idea at all what's happening or going wrong... :cry:

**Comment by arthurevans** [comment]
If you're using `dom-repeat` inside of a `<table>`, you're probably seeing the result of Edge not supporting templates natively: https://github.com/Polymer/polymer/issues/1567 ... Although they're supposed to be supported in Edge 13?

**Comment by David-Mulder** [comment]
Great news, I just updated Windows (and thus also Edge) and now mostly everything started working. There are some small styling issues and one small weird bug, but it seems whatever bug was causing all the problems is now resolved.
