### ISSUE TITLE
Array-index property or sub-property

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#53]
Do you support data binding with array index or sub-property? Say I have this data object:

```
[
  {
    "id": 1,
    "infoArray": [a, b, c],
    "infoObject": {
      "prop1": "var1"
    }
  }
]
```

and I want to build a table like this:

```
<paper-datatable data="{{data}}">
  <paper-datatable-column header="Info Array" property="infoArray.0"></paper-datatable-column>
  <paper-datatable-column header="Info Object" property="infoObject.prop1"></paper-datatable-column>
  <paper-datatable-column header="Info Array2" property="infoArray[0]"></paper-datatable-column>
</paper-datatable>
```

**Comment by David-Mulder** [comment]
Nope, but you can simply do

```
<paper-datatable-column header="Info Object" type="Object" property="infoObject">
  <template>
    {{value.prop1}}
  </template>
</paper-datatable-column>
```

the array example is a LOT harder though due to the way Polymer works (stuff like `array.0` isn't allowed in bindings although it sort of worked in the past). You would have to set up a `getItem` function on your `<paper-datatable-column>` and then write 

```
<paper-datatable-column header="Info Array" property="infoArray">
  <template>
    {{getItem(infoArray,0)}}
  </template>
</paper-datatable-column>
```

and even that wouldn't allow two way binding (you would need to use `<array-selector>` or a `<dom-repeat>` for that).

**Comment by NamTThai** [comment]
Agree with the array part. That's pretty irrelevant. 

Object binding doesn't work with sorting, btw. The sort function will compare `Object` instead of `Object.prop1`. What do you think about this?

**Comment by David-Mulder** [comment]
@NamTThai Totally aware of that, so that's what the `sort` attribute is for ;-) , check the 'sorting & type system' demo for that (the `object` column): http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/sorting.html

**Comment by NamTThai** [comment]
Awesome!
