### ISSUE TITLE
--paper-datatable-column-header mixin doesn't apply to the first column

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#54]
I have this mixin:

```
paper-datatable {
      --paper-datatable-column-header: {
        color: red;
      };
}
```

It works fine on selectable table:

![image](https://cloud.githubusercontent.com/assets/8039387/11702837/b3d17cbc-9e8e-11e5-90f0-14b6f86299df.png)

But it doesn't apply style to non-selectable table:

![image](https://cloud.githubusercontent.com/assets/8039387/11702798/65c78c14-9e8e-11e5-8540-b11d527e1d4a.png)

Did I miss out something? Thanks!

**Comment by David-Mulder** [comment]
Ah sorry, must have missed that, will fix!
