### ISSUE TITLE
Feature: input page size

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#58]
Would be great if there's a dom-if here with options for  a paper-input in addition to your paper-dropdown, the former allowing user to type in the number of rows per page they want (e.g. 8, 12, etc.)

https://github.com/David-Mulder/paper-datatable/blob/master/paper-datatable-card.html#L113

Also, a bug: if specifying `page-size` attribute not in `5, 10, 25, 100` then that number does not show up

**Comment by David-Mulder** [comment]
Yeah, my bad, actually knew I still had to do that but it seemed such an unlikely thing for people to change that I just ended up being lazy and simply implementing the suggested page sizes from the MD spec (though I might have changed them afterwards and removed the biggest one). Oh well, will definitely add. Probably will add an array attribute `page-size-options` and `page-size` will - as is now the case - need to be a valid option.
