### ISSUE TITLE
Feature: re-positioning after nextPage()

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#59]
If `paper-datatable-card` is located at end of page and there are content above, the table will jump up after nextPage(). This is possibly a consequence of using iron-pages. When clicking nextPage(), table content is repopulated. Therefore, the scroller becomes shorter because it extends again. This will cause the content to jump up during scroller's contraction

FIrst page:
![image](https://cloud.githubusercontent.com/assets/8039387/11732799/863f4486-9f5c-11e5-9913-9d5f3fc904a0.png)

After clicking next page:
![image](https://cloud.githubusercontent.com/assets/8039387/11732829/d6f29220-9f5c-11e5-81d4-494a5c981c1a.png)

This is a problem if user wants to skip several pages. They will have to scroll down again and again to see the bottom toolbar.

2 possible solutions:
- Remember offsetTop of the bottom toolbar and then scroll back to it after nextPage() is done.
- Fire an event after nextPage() is loaded and then let programer do what they want with it

**Comment by David-Mulder** [comment]
Puuuh, this is a hard one, I mean, the way the repopulation is programmed right now the table should actually _not_ become shorter between page switches... Either way, you can already listen for the `page-changed` event or an async trigger on next tick after the `dataSource.get`, but weeh, this sounds so weird. Could you share the following information:
- Shady or shadow DOM?
- Browser and OS version?
- Do you actually see the table being emptied? Does it look the same way as `/demo/complex-paper-datatable-card.html` does?

**Comment by NamTThai** [comment]
- I'm using Shady DOM
- Google Chrome  v47.0.2526.80 m on Windows 7

Anyway `page-changed` works!
