### ISSUE TITLE
Re-assigning data model

### ISSUE THREAD

**Issue by anhvupham** [David-Mulder/paper-datatable#62]
The scenario is you have a model which is array of 3 rows and you assign it to &lt;paper-datatable data="{{model}}" &gt;, then you change the model to 2 rows then paper-datatable is not reload with correct data.

**Comment by David-Mulder** [comment]
Are you using proper polymer functions to assign the new value of the array? Polymer 1.0 doesn't listen magically for array changes anymore, so for example from code you would need to use:

```
this.$.datatable.splice('data', 0, this.$.datatable.data.length);
this.$.datatable.push('data', ...);
```

Sadly enough I think from the top of my head polymer isn't even able to handle `.set('data', newArray)`, but as soon as polymer supports that by triggering the logical splice notifications it will magically work in this element as well.

**Comment by anhvupham** [comment]
Polymer does handle that, since I can use this.set("model", newModel) with &lt;template is="dom-repeat"&gt; and it reloads correct data. Looks like the attribute data-empty on the cell blocks this re-redendering.

**Comment by David-Mulder** [comment]
Okay, i will make sure to check, but seriously, change notifications are really quite weird when using set on parent level complex structures.

**Comment by David-Mulder** [comment]
Great, just wrote a long comment on my phone but lost it when I switched to Google maps for directions for a second. Either way, I think I have figured out what's happening and the problem might be that you're resetting internal polymer key collections which I assume to be constant. I have been thinking about a `reset` function, but properly resetting the entire element is... Harder than it sounds. Either way, the solution above I mentioned should definitely work.

**Comment by anhvupham** [comment]
Well, as long as the table would be reset along with model then it will work. The common case is that you have a search input which request to API to refresh the model and then try to have the paper-datatable re-rendered too. If that could be solved than it is just great.

**Comment by David-Mulder** [comment]
Just got home and yeah, my theory about what's causing the issue was correct. Not sure how I am going to solve this, but it should be fixable~

**Comment by anhvupham** [comment]
Awesome, can you update bower ? Thanks.

**Comment by David-Mulder** [comment]
@anhvupham Oops, yeah, I tend to forget pushing out new releases all the time. You can now pull it through bower as well. And just a tip, you can always set a certain version in your bower file, but pull in `#master` on request in bower.
