### ISSUE TITLE
Default value 0

### ISSUE THREAD

**Issue by NamTThai** [David-Mulder/paper-datatable#66]
When I set default value of paper-datatable-column to 0 and type Number, it shows up as NaN:

![image](https://cloud.githubusercontent.com/assets/8039387/11886606/bc5543b6-a4e0-11e5-87c8-13da941256ff.png)

**Comment by David-Mulder** [comment]
Falsy values are a pain with Polymer, will check.

**Comment by David-Mulder** [comment]
Sorry for taking so long, wasn't even due to polymer, just a stupid mistake on my part
