### ISSUE TITLE
Allow sort function on a column level

### ISSUE THREAD

**Issue by xmakro** [David-Mulder/paper-datatable#71]
Example:

```
<paper-datatable-column header="Forename" property="forename" type="String" sortable></paper-datatable-column>
<paper-datatable-column header="Birthday" property="birthdate" type="String" sortable="{{compareBirthday}}"></paper-datatable-column>

function compareBirthdate(a, b) {
    // compare a with b which are both birthdate strings
    // returns either negative number, 0 or positive number
    // if sort order is desc, then a and b are swapped by the datatable before calling this function
}
```

Proposal: Allow function passing to the sortable property of a datatable-column. If no function is passed, default comparison is used.

**Comment by David-Mulder** [comment]
This is already possible, see http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable/sorting.html and then the `Object` column. If this doesn't provide everything you need let me know, will close for now.
