### ISSUE TITLE
Port for Dart

### ISSUE THREAD

**Issue by supermuka** [David-Mulder/paper-datatable#74]
I would like know if there is a version the paper-datatable for Dart lang.

**Comment by zoechi** [comment]
you can try the Dart package custom_element_apigen to generate Dart wrappers like the Dart polymer_elements package was created

**Comment by supermuka** [comment]
I never used the Dart package custom_element_apigen. I will study the documentation and to try use it. I hope to have good results! Thank you!

**Comment by supermuka** [comment]
@zoechi, did you get to run paper-datatable after generate Dart wrappers with custom_element_apigen? I had a little work to generated and after it does not appear on my application. On debug mode, when I import paper_datatable.dart, pub serve works fine, but the following error is displayed on console (Failed to execute 'registerElement' on 'Document': Registration failed for type 'iron-meta'. A type with that name is already registered.). Do you know what could be occuring?

**Comment by zoechi** [comment]
@supermuka I haven't used it myself but I have see it  mentioned several times that people succeeded. 
Do you get any errors?

**Comment by supermuka** [comment]
I commented briefly above. The application works, but  the paper-datatable is ignorated, does not appear!

**Comment by zoechi** [comment]
Sorry, didn't read the full comment. Create an issue in the GitHub repo of custom_element_apigen. It's likely that you get competent support there.
