### ISSUE TITLE
Change color of paper-progress

### ISSUE THREAD

**Issue by IchordeDionysos** [David-Mulder/paper-datatable#89]
Hey David,

I love this element too, and found a very good use on our [website](https://deepspace.onl/gaming/), but  it would be great to customize the color of the paper-progress to adapt it to the theme of our website

Dennis

**Comment by RoXuS** [comment]
You can already do that, just set :

```
--paper-progress-active-color: color;
--paper-progress-container-color: color;
```

In you parent component like this :
https://github.com/David-Mulder/paper-datatable/blob/master/demo/miscellaneous/theming.html#L31
