### ISSUE TITLE
mixin ES2015 code breaks down gulp-vulcanize

### ISSUE THREAD

**Issue by wuyuanyi135** [David-Mulder/paper-datatable#90]
Hello.
I just started use paper-datatable but it didn't work with my build process. It stopped my gulp-vulcanize with error

```
Error: no writecb in Transform class
```

After tracing the code, I found these arrow functions `=>` at line 513, 522, 567, 590, 648, 1088. By commenting them the build task succeeded.

The command line vulcanize actually can do this, but I don't know what happens to gulp version.

I also open the issue in [vulcanize](https://github.com/Polymer/vulcanize/issues/306).

**Comment by RoXuS** [comment]
Hello,

What is your version ? We use gulp-vulcanize 6.0.1 and we don't have this issue.

**Comment by wuyuanyi135** [comment]
@RoXuS It was 6.1.0. I will try your suggestion. Thank you.

**Comment by RoXuS** [comment]
I have tested in 6.1.0 and it is ok.
I think your node version is deprecated ? This error seems appear when your node version is too old, I use the last version of node (v5.6.0).

**Comment by wuyuanyi135** [comment]
I have upgrade node to 5.6.0 but It did not help

**Comment by wuyuanyi135** [comment]
@RoXuS Can you share your gulp-vulcanize options?

``` js
    var option = {
        abspath: '',
        excludes: [],
        inlineScripts: true,
        stripExcludes: false
    };
```

**Comment by wuyuanyi135** [comment]
Turned out not a problem of gulp-vulcanize.... the polyclean.uglifyJs() did. Do you use polyclean?

**Comment by RoXuS** [comment]
@wuyuanyi135 nop, I don't use polyclean.

Polyclean uses UglifyJS2 and it isn't compatible with ES6, follows this issue : https://github.com/mishoo/UglifyJS2/issues/448#issuecomment-136495040

For now, I think it is better to use polyclean on your own components and not on your dependencies.

Another solution is not to use it (for info, the polymer starter kit does not use this tool https://github.com/PolymerElements/polymer-starter-kit).

**Comment by wuyuanyi135** [comment]
Thank you for the information!
