### ISSUE TITLE
is there a way to put date to coloumns ???

### ISSUE THREAD

**Issue by arangates** [David-Mulder/paper-datatable#93]
like the one shown below

![screenshot from 2016-02-29 23-37-23](https://cloud.githubusercontent.com/assets/7692801/13403984/9d92cd44-df3d-11e5-9d6f-59efa0a59c9b.png)

**Comment by RoXuS** [comment]
Yeah you just have to use an external component like this :

```
<paper-datatable-column header="Date">
  <template>
    <moment-js date="[[value]]" dateFormat="YYYY-MM-DD"></moment-js>
  </template>
</paper-datatable-column>
```

moment-js is available here : https://github.com/saeidzebardast/moment-js.
I have never used this component (we use our own date component) but it seems ok.

**Comment by arangates** [comment]
Thanks man...i will checkout !
